FROM maven:3.6.1-jdk-8-slim 
SHELL ["/bin/bash", "-c"]
RUN apt-get update && apt-get install --no-install-recommends -y git
RUN git clone https://b17b4687a695ae9c471c6b3b05ce0394087a5547:x-oauth-basic@github.com/TomomasaTakatori/biz-energygateway-prep-SelectFeatureColumns
WORKDIR biz-energygateway-prep-SelectFeatureColumns
RUN mvn compile
