FROM maven:3.6.1-jdk-8-slim 
SHELL ["/bin/bash", "-c"]
RUN apt-get update && apt-get install --no-install-recommends -y git
RUN git clone -b develop https://b86404928c0b9ef6b73dfd158675e3fee608985d:x-oauth-basic@github.com/TomomasaTakatori/biz-energygateway-prep-PreProcessingCollection
WORKDIR biz-energygateway-prep-PreProcessingCollection
RUN mvn compile
