FROM maven:3.6.1-jdk-8-slim
SHELL ["/bin/bash", "-c"]
RUN apt-get update && apt-get install --no-install-recommends -y git
RUN sed -e '54a <localRepository>/root/.m2/repository</localRepository>' /usr/share/maven/ref/settings-docker.xml
RUN git clone https://c0d844696604939dafcaaa204cdc371d660d7395:x-oauth-basic@github.com/TomomasaTakatori/biz-energygateway-prep-PreProcessingCollection
WORKDIR biz-energygateway-prep-PreProcessingCollection
RUN mvn install:install-file -Dfile=lib/openapi-java-client-0.0.2-jar-with-dependencies.jar -DgroupId=org.openapitools  -DartifactId=openapi-java-client -Dversion=0.0.2 -Dpackaging=jar
RUN mvn compile
